"""add_leave_requests_extra_metadata

Revision ID: 117e93df4f10
Revises: e98e85ec0f02
Create Date: 2026-08-17 18:48:40.115777

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "117e93df4f10"
down_revision: Union[str, Sequence[str], None] = "e98e85ec0f02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leave_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("extra_metadata", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leave_requests", schema=None) as batch_op:
        batch_op.drop_column("extra_metadata")

    # ### end Alembic commands ###
