"""add_rejection_reason_to_timesheet_entries

Revision ID: 218557040b65
Revises: cd0bc963b952
Create Date: 2026-08-10 16:05:08.192762

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "218557040b65"
down_revision: Union[str, Sequence[str], None] = "cd0bc963b952"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("timesheet_entries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rejection_reason", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("timesheet_entries", schema=None) as batch_op:
        batch_op.drop_column("rejection_reason")

    # ### end Alembic commands ###
