"""remove_hours_spent_and_use_total_minutes_spent

Revision ID: e19fe4f66ff4
Revises: 117e93df4f10
Create Date: 2026-08-19 17:50:51.391484

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e19fe4f66ff4"
down_revision: Union[str, Sequence[str], None] = "117e93df4f10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("timesheets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "total_minutes_spent", sa.Integer(), server_default="0", nullable=False
            )
        )
        batch_op.drop_column("hours_spent")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("timesheets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "hours_spent",
                sa.NUMERIC(precision=5, scale=2),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("total_minutes_spent")

    # ### end Alembic commands ###
