"""rename timesheet entries to timesheets with json activity

Revision ID: e98e85ec0f02
Revises: 218557040b65
Create Date: 2026-08-17 16:03:05.773731

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e98e85ec0f02"
down_revision: Union[str, Sequence[str], None] = "218557040b65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if "timesheets" not in tables:
        op.create_table(
            "timesheets",
            sa.Column("id", sa.UUID(as_uuid=True), primary_key=True),
            sa.Column(
                "user_id",
                sa.UUID(as_uuid=True),
                sa.ForeignKey("users.id", ondelete="CASCADE"),
                nullable=False,
            ),
            sa.Column(
                "project_id",
                sa.UUID(as_uuid=True),
                sa.ForeignKey("projects.id", ondelete="SET NULL"),
                nullable=True,
            ),
            sa.Column("work_date", sa.Date(), nullable=False),
            sa.Column("hours_spent", sa.Numeric(precision=5, scale=2), nullable=False),
            sa.Column("is_billable", sa.Boolean(), default=True, nullable=False),
            sa.Column("activity_summary", sa.JSON(), nullable=False),
            sa.Column(
                "status", sa.String(length=20), default="submitted", nullable=False
            ),
            sa.Column(
                "approver_id",
                sa.UUID(as_uuid=True),
                sa.ForeignKey("users.id", ondelete="SET NULL"),
                nullable=True,
            ),
            sa.Column("rejection_reason", sa.Text(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        )

    if "timesheet_entries" in tables:
        op.drop_table("timesheet_entries")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if "timesheets" in tables:
        op.drop_table("timesheets")

    if "timesheet_entries" not in tables:
        op.create_table(
            "timesheet_entries",
            sa.Column("id", sa.UUID(as_uuid=True), primary_key=True),
            sa.Column(
                "user_id",
                sa.UUID(as_uuid=True),
                sa.ForeignKey("users.id", ondelete="CASCADE"),
                nullable=False,
            ),
            sa.Column(
                "project_id",
                sa.UUID(as_uuid=True),
                sa.ForeignKey("projects.id", ondelete="SET NULL"),
                nullable=True,
            ),
            sa.Column("work_date", sa.Date(), nullable=False),
            sa.Column("hours_spent", sa.Numeric(precision=5, scale=2), nullable=False),
            sa.Column("is_billable", sa.Boolean(), nullable=False),
            sa.Column("activity_summary", sa.Text(), nullable=False),
            sa.Column("status", sa.String(length=20), nullable=False),
            sa.Column(
                "approver_id",
                sa.UUID(as_uuid=True),
                sa.ForeignKey("users.id", ondelete="SET NULL"),
                nullable=True,
            ),
            sa.Column("rejection_reason", sa.Text(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        )
    # ### end Alembic commands ###
